update config

diff --git a/bin/start-nginx b/bin/start-nginx
--- a/bin/start-nginx
+++ b/bin/start-nginx
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
+if [ -z $1 ]
+  echo "Missing $1 argument (HOME_DIR)"
+  exit 1
+fi
 HOME_DIR=$1
 APP_DIR=$HOME_DIR/app
+
 
 echo "Working directory: $APP_DIR"
 
@@ -53,14 +58,15 @@ rm -f $psmgr
 mkfifo $psmgr
 
 # Initialize log directory.
-mkdir -p $APP_DIR/logs/nginx
-touch $APP_DIR/logs/nginx/access.log $APP_DIR/logs/nginx/error.log
+touch $APP_DIR/logs/access.log
+touch $APP_DIR/logs/error.log
+
 echo 'buildpack=nginx at=logs-initialized'
 
 # Start log redirection.
 (
   # Redirect nginx logs to stdout.
-  tail -qF -n 0 $APP_DIR/logs/nginx/*.log
+  tail -qF -n 0 $APP_DIR/logs/*.log
   echo 'logs' >$psmgr
 ) &
 
